### ISSUE TITLE
Introduction to CI/CD with GitHub Actions

### ISSUE THREAD

**Issue by sudomateo** [CodeandCoffeeCommunity/speaking#11]
## About You

**Your Name:**

Matthew Sanabria

**Twitter handle (optional):**

[sudomateo](https://twitter.com/sudomateo)

**The best way to reach out to you:**
- Twitter (sudomateo)
- Discord (sudomateo#7418)

**A quick bio:**

Matthew Sanabria is an Engineer at HashiCorp and a former Adjunct Instructor at New Jersey Institute of Technology (NJIT). At HashiCorp, Matthew develops Terraform Enterprise, mentors other engineers, and contributes to the [Terraform Associate](https://www.hashicorp.com/certification/terraform-associate) certification exam. At NJIT, Matthew designed and taught a new curriculum for the IT340 Introduction to System Administration course. With over 7 years of professional and teaching experience, Matthew enjoys mentoring others and contributing back to the community.

## Your Talk

**Title:**

Introduction to CI/CD with GitHub Actions

**What your talk is about:**

Use GitHub Actions to lint your code, build a Docker image, and deploy that Docker image to a registry.

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [x] 20-30 minutes
- [x] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [x] No

## Meetup event Copy - Optional

**Event Title:**

New York Code & Coffee

**Event Description:**

**Comment by SteveChenDC** [comment]
@Danamitecoder could you get in contact with Matt to schedule this talk? This seems like an incredibly exciting talk.

**Comment by Danamitecoder** [comment]
Absolutely! Thanks for the heads up, Steve! Do you know if there’s any way
I can get notified whenever people submit an issue on this repository in
GitHub?

**Comment by Danamitecoder** [comment]
Hi @sudomateo ! Thank you for expressing interest in giving a talk to NYC code and coffee! I will contact you on Discord/Twitter for a follow-up conversation.

**Comment by sudomateo** [comment]
@Danamitecoder sorry for the delay on this. I'm putting together my code example in https://github.com/sudomateo/github-actions-introduction and I'm working on my presentation slides. I'll post another message on this issue once they are ready.

**Comment by sudomateo** [comment]
I'm closing this for now since I haven't had the time to attend meetups. I'll reopen if things change on my end.
