### ISSUE TITLE
How I built data pipeline as a One-Person Data Team in early stage startup 

### ISSUE THREAD

**Issue by dq-hustlecoding** [CodeandCoffeeCommunity/speaking#12]
## About You

**Your Name:** DQ Choi

**Twitter handle (optional):** 

**The best way to reach out to you:** dq.choi@momenti.tv

**A quick bio:** 8+ years experienced data scientist/engineer 
data engineer at @corp-momenti (see our homepage [here](https://momenti.tv))
Worked for various early stage startups
author of "Build Your Own Netflix" (in progress) 

## Your Talk

**Title:** How I Built a Data Pipeline from Scratch as a One-Person Data Team: A Practical Guide

**What your talk is about:**
A year ago, I joined Momenti, a new media platform startup, as the sole member of the data team. The existing data pipelines were built on GCP Spanner and Elixir, which were decent but too costly for an early-stage startup with a limited budget. Therefore, I decided to create a new data pipeline from scratch using GCP Pubsub and Bigquery and NestJS server. As a result, we were able to reduce our GCP usage fee by up to 90% compared to the previous pipeline. In this talk, I will share the insights and challenges I gained from this journey, as well as the areas for further improvement.

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [x ] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [x ] No

## Meetup event Copy - Optional
**Event Title:**   
  
**Event Desciption:**

**Comment by Danamitecoder** [comment]
Hi DQ Choi! Thank you so much for submitting a request to give a talk at a future Code and Coffee. I'll email you directly so we can touch base regarding your talk and next steps!
