### ISSUE TITLE
Getting Started With Amplify For Web Developers

### ISSUE THREAD

**Issue by ErikCH** [CodeandCoffeeCommunity/speaking#13]
## About You

**Your Name:**
Erik Hanchett

**Twitter handle (optional):** 
ErikCH

**The best way to reach out to you:**
Twitter

**A quick bio:**
I'm a developer advocate for Amplify at AWS. I've worked as a software developer for many years at small startups, larger companies and everything in between. When I'm not teaching people, or creating tutorials, I love puzzles and spending time with my family.

## Your Talk

**Title:**
Getting Started With Amplify For Web Developers

**What your talk is about:**

AWS offers a lot of services. Cognito, S3, Hosting, and Lambda functions to name a few. What if we could access those services without having to learn devops, infrastructure as code, and intricate IAM rules? So as front-end developers we can focus on the front-end.

Amplify has us covered! In this talk I'll discuss how to get started with Amplify, how it can be used by Front-end and mobile developers to use AWS services and some of the nice features it has. This will include:

* UI Components Library
* Authentication connected components
* Amplify Studio with our Figma to Code integration

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [x] 20-30 minutes
- [x] 30-45 minutes
- [ ] 60 minutes or more

## Meta
I travel a lot for work, so if chosen I'd love to deliver this talk in late April or May. :)

**Do you need help crafting your talk?**
- [ ] Yes
- [x] No (But I could always use a set of eyes to look over the talk before I deliver it)

## Meetup event Copy - Optional
**Event Title:**   
  
**Event Desciption:**

**Comment by Danamitecoder** [comment]
Hi Erik! Thank you for expressing interest in giving a talk! Would you be available sometime this week to discuss next steps?

**Comment by ErikCH** [comment]
Hi @Danamitecoder ! Sure let me know

**Comment by Danamitecoder** [comment]
@ErikCH What is your email?

**Comment by ErikCH** [comment]
It was nice chatting with you @Danamitecoder Looking forward to our next conversation in April. Hoping we can get a date down for May 28th.

**Comment by Danamitecoder** [comment]
Sure! Could you let me know when you are done with the slide deck? We can set up a follow-up conversation where we will finalize a date for your talk. Thank you!

**Comment by ErikCH** [comment]
Hi! Hopefully we are all set for this on June 4th! For a live workshop.

**Comment by SteveChenDC** [comment]
@ErikCH Yup! Just made the meetup event https://www.meetup.com/new-york-code-coffee/events/293800603/  

I'll also personally be driving up from DC for this C&C! Looking forward to meeting you
