### ISSUE TITLE
Building a Smart Dashboard for Your Amazon Shopping Habits with Retool and Google Sheets

### ISSUE THREAD

**Issue by ajot** [CodeandCoffeeCommunity/speaking#15]
## About You

**Your Name:**
Amit Jotwani

**Twitter handle (optional):** 
https://twitter.com/amit

**The best way to reach out to you:**
Twitter

**A quick bio:**
Hello! I am Amit, a Senior Developer Advocate at [Retool](https://retool.com/). Prior to joining Retool, I spent five years at Amazon, helping developers build voice skills for Alexa. By day you can find me cooking up Retool apps to solve my everyday problems. By night, when I am not doing dad duties or cooking up code, I like catching up on the reruns of Seinfeld. Self-proclaimed Lego, and Instant Pot recipe nerd.

## Your Talk

**Title:**
Building a Smart Dashboard for Your Amazon Shopping Habits with Retool and Google Sheets

**What your talk is about:**
Have you ever wondered how much you spent shopping on Amazon?

My wife and I became parents last year, and that meant a lot of baby related shopping on Amazon. As these little brown boxes piled up, we started wondering how much we'd spent on Amazon in general, and on baby supplies in particular. What categories did we spend the most on? What was our biggest baby-related expense? 

I thought it would be pretty cool if there was some sort of dashboard that would be give me insights of our Amazon shopping for the year.

In this session, I'll walk you through how I built this dashboard using a combination of Google Sheets, Retool, and even a splash of ChatGPT.

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [x] 20-30 minutes
- [ ] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [x] No

## Meetup event Copy - Optional
**Event Title:**   
  
**Event Desciption:**

**Comment by Danamitecoder** [comment]
Hi Amit! Thank you for submitting a request to give a talk! I will reach out to you via Twitter to discuss next steps :)

**Comment by Danamitecoder** [comment]
-Introductions
-Helloworld
-App 1 - Amazon, ChatGPT 
-Questions
