### ISSUE TITLE
Front end development for beginners | Boston Chapter | In person

### ISSUE THREAD

**Issue by parthasarathydNU** [CodeandCoffeeCommunity/speaking#17]
## About You

**Your Name:**
Dhruv Parthasarathy

**Twitter handle (optional):** 

**The best way to reach out to you:** 
Whatsapp +1 412-450-7755, 
LinkedIn: https://www.linkedin.com/in/parthasarathydhruv/
Email: Parthasarathy.d@northeastern.edu

**A quick bio:**
I am an experienced software developer with a passion for building fast and responsive user interfaces and optimizing web application performance. 

I am currently pursuing a Master's degree in Software Engineering Systems at Northeastern University in Boston. In my three years in the software development industry, I have developed a range of technical skills, including expertise in React, Redux, D3, ThreeJS, AngularJS, Java, Node, Socket.io, RabbitMQ, Postgres, MySQL, Git, and Protractor.

I am self-motivated and a quick learner, and I am comfortable working with a variety of technologies. However, I believe that the end-user experience is the most important consideration, rather than the specific technologies used to achieve it. 

My personal mantras are "learning over knowing" and "quality over quantity".

## Your Talk

**Title:**
Front End Development for Beginners | Boston C&C Meetup

**What your talk is about:**
What is front end development and what abilities does a front end developer possess.
Introduction to HTML, CSS, Javascript and ReactJS

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [ ] 30-45 minutes
- [x] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [x] No

## Meetup event Copy - Optional
**Event Title:**   
  
**Event Desciption:**

**Comment by SteveChenDC** [comment]
👀  Will be reaching out shortly!
