### ISSUE TITLE
Intro to NEARPrimer - the dualingo for learning about blockchain

### ISSUE THREAD

**Issue by humanman** [CodeandCoffeeCommunity/speaking#18]
## About You

**Your Name:**

Ben Sayeg

**Twitter handle (optional):** 
@benthehumanman1 

**The best way to reach out to you:**

Benson.sayeg@near.foundation

**A quick bio:**

Ben Sayeg has been working in education, outreach, and support within NEAR Foundation since 2021. Currently, he is leading the efforts in content strategy helping founders on their journeys to launch successful Web3 businesses in the NEAR ecosystem. He is passionate about breaking down complex concepts without breaking any brains.

## Your Talk

**Title:**
Intro to NEARPrimer the dualingo for learning blockchain development 

**What your talk is about:**
I want to promote a fantastic learning app called nearprimer.com. It provides a fun, casual way to wrap your head around blockchain development. I think it’s perfect for jr developers interested in blockchain that may find it too daunting to pursue. I’d like to go over the basics of the app, and walk through one of the “quests” where you learn how smart contracts work. 

**How long will your talk be?**
- [ x] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [ ] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [x ] No

## Meetup event Copy - Optional
**Event Title:**   

  Finally a fun way to learn about blockchain development without melting your brain

**Event Desciption:**  

Meet NEARPrimer! A fun, casual way to learn about blockchain development and how to build on NEAR Protocol

**Comment by Danamitecoder** [comment]
This talk has been delivered.
