### ISSUE TITLE
Natural Language Processing and Sentiment analysis using Machine Learning - Applications - Open AI - Chat GPT 

### ISSUE THREAD

**Issue by Abhimba1992** [CodeandCoffeeCommunity/speaking#19]
## Talk Request

**Topic(s):**
Natural Language Processing and Sentiment analysis using Machine Learning - Applications - Open AI - Chat GPT 
**Additional Notes:**
Written a year long Research, I present the abstract of my technical paper
Abstract: 
This project presents a Sentiment Analysis System which uses Enhanced Naïve Bayes
Classifier for performing Sentiment Analysis on Book reviews. This system is capable
of reading reviews on books, understanding the sentiment of each review and rate the
book accordingly. The review is read from the user input. The system then interprets
the part of speech and then polarity of the review. The rating system acts in
accordance to the outputs that it receives. It is also capable of improving the classifier
by adding features for handling Laplacian Smoothing, N grams, Negation Handling,
Feature Selection and Mutual Information, hence formulated as the Enhanced Naïve
Bayes Classifier. This gives us a more efficient Classifier than the original Naïve
Bayes Classifier to perform Sentiment Analysis.

**What would the ideal length be?**
- [x] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [ ] 30-45 minutes
- [ ] 60 minutes or more

## On Behalf Of

**Requesting people or Meetups:**
Meetups 
**The best way to reach out to them:**
email : abhimba1992@gmail.com

**Comment by Danamitecoder** [comment]
Hi Abhimba, I will reach out to you via. email to set up a time to talk! Thanks for your interest!

**Comment by Danamitecoder** [comment]
Tentative talk date: Sunday 4/30...possibly 4/16
Slide Deck Touch Base / Feedback: 4/9 - 8am MDT / 9am CT
