### ISSUE TITLE
Building Modern Applications with Non Relational Databases (NoSQL)

### ISSUE THREAD

**Issue by carbsandtiktoks** [CodeandCoffeeCommunity/speaking#20]
## About You

**Your Name:**
Sheyla Ruiz

**Twitter handle (optional):** 
carbsandtiktoks
**The best way to reach out to you:**
Email: sheyla.ruizflete@couchbase.com
**A quick bio:**
As part of Couchbase's Community team, I'm always looking for fun and interesting resources to share with developers. You can also catch me searching for the latest meme, playing video games, or obsessing over a korean drama.
## Your Talk

**Title:**
Building Modern Applications with Non Relational Databases (NoSQL)

**What your talk is about:**
The session will cover the concepts of Non-relational databases. An in-depth understanding of how non-relational databases are helping modern applications scale and outcome performance over traditional relational databases. Attendees will also get insights into existing nonrelational databases in the market and demo on Couchbase Capella where we will execute queries and show performance. 

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [x] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [x] No

## Meetup event Copy - Optional
**Event Title:**   
Building Modern Applications with Non Relational Databases (NoSQL)
**Event Description:**  
NY Code & Coffee - join us for a bit of Show and Tell!

**The Tell**
The session will cover the concepts of Non relational databases. We'll take a deep dive into how non relational database are helping modern applications outperform and scale versus a traditional relational database.
**The Show**
We'll walk you through how existing non relational databases in the market perform followed by a live demo where we will execute queries and evaluate performance on the comfiest couch in DBaaS: Couchbase Capella.

**Comment by Danamitecoder** [comment]
Next Thursday/Friday (4/13, 4/14) - Slide deck should be ready

**Comment by carbsandtiktoks** [comment]
Hi @Danamitecoder!

(love your username)

We updated our talk as we ran into some technical limitations for the demo. I sent you an email with more details. Thanks!
