### ISSUE TITLE
Developing Data Skills To Fast-track Your Career

### ISSUE THREAD

**Issue by edwinmsarmiento** [CodeandCoffeeCommunity/speaking#21]
## About You

**Your Name:**
Edwin M Sarmiento

**Twitter handle (optional):** 
https://www.twitter.com/EdwinMSarmiento

**The best way to reach out to you:**
LinkedIn: https://www.linkedin.com/in/EdwinMSarmiento
Email: edwinmsarmiento@outlook.com

**A quick bio:**
Edwin M Sarmiento is the Managing Director of 15C, a consulting company that specializes in designing, implementing, and managing high-availability infrastructures. He is a former Microsoft Data Platform MVP of 12 years standing, a Microsoft Certified Master for SQL Server, and author of the book [The SQL Server DBA's Guide to Docker Containers](https://www.amazon.com/Server-Guide-Docker-Containers-Lock/dp/1484258258). He is very passionate about technology, and has interests in music, social psychology, professional and organizational development, leadership, and management matters when not working with databases. 

## Your Talk

**Title:**
Developing Data Skills To Fast-track Your Career

**What your talk is about:**
British mathematician Clive Humby coined the phrase, "Data is the new oil." 

Those who can make sense of the massive growth of data can use it as a competitive advantage.  Companies like Target, Amazon, and Facebook used data they collected to grow their profits. 

If businesses can use data to accelerate their growth, as a tech professional, you can, too.   

Whether you're still a student who wants to break into tech or a tech professional with years of experience, learn how you can develop data skills that will help you get hired, promoted, and paid much faster than your peers. And you don't need to be working in data and analytics. These skills are applicable whether you're a developer, a cloud engineer, or even a helpdesk technician.

I will share practical tips and tricks from decades of experience working in tech that you can immediately apply the next day. 

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [ ] 30-45 minutes
- [x] 60 minutes or more (including Q&A)

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [x] No

## Meetup event Copy - Optional
**Event Title:**   
  
**Event Desciption:**

**Comment by Danamitecoder** [comment]
Hi Edwin,

I've reached out to you on LinkedIn regarding to set up a time to talk about the talks you would like to give. 

Thanks!
Dana

**Comment by Danamitecoder** [comment]
This talk has been scheduled for 4/30!
