### ISSUE TITLE
Talk 04/16/2023

### ISSUE THREAD

**Issue by mehertech55** [CodeandCoffeeCommunity/speaking#25]
## About You

**Your Name:**
Meher Upadhyay

**Twitter handle (optional):** 

**The best way to reach out to you:**
5512632578 or meheruoffice@gmail.com

**A quick bio:**
Currently working as Software Engineer III at Walmart Global Tech. 

## Your Talk

**Title:**
Algorithms and Sensors

**What your talk is about:**
Choosing an advanced algorithm course(implementation of Van Emde bas tree and binary tree)
Notification System, IoT device that notifies when water quality goes bad, Sonification of data(Projects delivered during my Masters in Computer Science at Pace University) Petition with United Nations

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [x] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [x] Yes
- [ ] No

## Meetup event Copy - Optional
**Event Title:**   
https://www.meetup.com/new-york-code-coffee/events/292634630/
  
**Event Description:**  
--

**Comment by Danamitecoder** [comment]
Hi Meher! Thanks for giving the talk. It was wonderful collaborating with you on this :)
