### ISSUE TITLE
How video tech works, on the web 🌐 2023

### ISSUE THREAD

**Issue by arturparkhisenko** [CodeandCoffeeCommunity/speaking#27]
## About You

**Your Name:** Artur Parkhisenko

**Twitter handle (optional):** none

**The best way to reach out to you:** LinkedIn

**A quick bio:** Sr. Software Engineer at Vimeo OTT, working on apps with video tech on different platforms. Have some experience giving talks in the past.

## Your Talk

**Title:** How video tech works, on the web 🌐 2023

**What your talk is about:** A simple sneak peek into how video works on the web. A bit of history, demo, and examples of how-to, minimal learning path, and other resources.

**How long will your talk be?**

- [ ] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [x] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**

- [ ] Yes
- [x] No, but a slides review would be good.

## Meetup event Copy - Optional

**Event Location:** NYC

**Event Title:**
  
**Event Desciption:**

**Comment by arturparkhisenko** [comment]
cc @Danamitecoder for visibility :)

**Comment by Danamitecoder** [comment]
7/2 - connected on Linkedin!

**Comment by arturparkhisenko** [comment]
Feedback:
- Expand on the description.

**Comment by arturparkhisenko** [comment]
An updated description:
```
An introduction to how video tech works on the web.
We'll cover what is video, a bit of history, and what is commonly known about the media files with a quick demo.
Additionally, we will cover a learning tech minimum, share valuable community insights, and provide information on other helpful resources related to video technology.
```

**Comment by arturparkhisenko** [comment]
We did it :) Thanks!
