### ISSUE TITLE
Database Caching

### ISSUE THREAD

**Issue by ijoo123** [CodeandCoffeeCommunity/speaking#28]
## Talk Request
**Name:** Ijoo Yoon
**The best way to reach out to you:** LinkedIn
**Quick Bio:** Software Engineer currently contributing to Open Source Products, working on a product that deploys Kafka clusters,
**Topic(s):** Database Caching

**Additional Notes:**

**What would the ideal length be?**
- [X] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [ ] 30-45 minutes
- [ ] 60 minutes or more

## On Behalf Of

**Requesting people or Meetups:**

**The best way to reach out to them:**

**Comment by Danamitecoder** [comment]
Contacted via Linkedin - proposed 3 times for initial touch base.

**Comment by Danamitecoder** [comment]
8/17 - Discussed speaking proposal
8/24 - Deck Review

**Comment by Danamitecoder** [comment]
Event created, will be announced soon
