### ISSUE TITLE
Runtime Control (Flexing Flags)

### ISSUE THREAD

**Issue by mvittiglio** [CodeandCoffeeCommunity/speaking#31]
## About You

**Your Name:**
Michael Vittiglio

**Twitter handle (optional):** 

**The best way to reach out to you:**
michael.vittiglio@getunleash.io

**A quick bio:**
With over 25 years I've had the privilege of working in tech, I've enjoyed helping people in support roles, development roles, and (perhaps finally!) solutions engineering. These last few years, solving intriguing problems in the flagging space which I feel is not only making a big impact now but whose potential is only just starting to be realized (bigger things to come!)

## Your Talk
**Title:**
Runtime Control (Flexing Flags)

**What your talk is about:**
We only know of flagging as feature management leading to only relying on the classic switch metaphor. The technology is capable of so much more but the potential is impeded by the lack of exposure and understanding. Being able to adjust discrete values, engage in creative use of targeting rules, and more at runtime are capabilities that open doors to a lifecycle that is either unattainable or impractical without flags. These benefits, typically attributed to the end of the release cycle, actually manifest from the moment they are engaged.

We will start from the beginning with an introduction to the basics then move into the more complex capabilities (in the simplest of terms as possible) to, hopefully, inspire.

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [x] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [x] No

## Meetup event Copy - Optional
**Event Title:**   
  
**Event Description:**

**Comment by Danamitecoder** [comment]
Outreach on 8/11 to schedule first conversation regarding talk - proposed 3 available times

**Comment by Danamitecoder** [comment]
Cancelled
