### ISSUE TITLE
Recursion

### ISSUE THREAD

**Issue by Adam-Thometz** [CodeandCoffeeCommunity/speaking#32]
## About You

**Your Name:** Adam Thometz

**The best way to reach out to you:**  
[Linkedin](https://www.linkedin.com/in/adam-thometz/)
Email: adamthometz@gmail.com  

**A quick bio:**  
Independent contractor with 2 YOE. Trained on full-stack software development, working on DSA fundamentals.

## Your Talk

**Title:** Understanding Recursion

**What your talk is about:**
Recursion is one of the hardest things for folks to wrap their heads around at first. This time will be spent visualizing how recursion works, when to use it, how to implement it, and how to optimize it. I will demonstrate using a function that determines Fibonacci numbers (a classic interview question). If there is enough time, we can work independently on a harder problem.   

The language used will be Javascript.  

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [X] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [X] No

## Meetup event Copy - Optional
**Event Title:**   
  
**Event Description:**

**Comment by Danamitecoder** [comment]
8/22 - Messaged on Linkedin
