### ISSUE TITLE
Building Secure Websites

### ISSUE THREAD

**Issue by charlesinwald** [CodeandCoffeeCommunity/speaking#33]
## About You

**Your Name:** 
Charles Inwald

**Twitter handle (optional):** 

**The best way to reach out to you:** 
Phone or Discord

**A quick bio:** 
Former Apple Engineer, previously worked in startups as a frontend developer

## Your Talk

**Title:** 
Building Secure Websites

**What your talk is about:** 
Learn about the critical importance of web security, highlighting potential threats such as Cross-Site Scripting and SQL Injection.  Delve into the principles of secure web design, the vital role of HTTPS, and strategies for safeguarding sensitive data.

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [X] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [X] No

## Meetup event Copy - Optional
**Event Title:**   
Building Secure Websites
  
**Event Desciption:**   
Learn about the critical importance of web security, highlighting potential threats such as Cross-Site Scripting and SQL Injection.  Delve into the principles of secure web design, the vital role of HTTPS, and strategies for safeguarding sensitive data.  Bringing a laptop is optional.

**Comment by charlesinwald** [comment]
Slide Deck: https://docs.google.com/presentation/d/1O_aBBQseBjG3UIvBPeBG3XvrQDbcoswKwVkvXmEIS-U/edit?usp=sharing

**Comment by Danamitecoder** [comment]
8/22/23 Outreach performed, reviewed deck, scheduled
