### ISSUE TITLE
Introduction to DevOps

### ISSUE THREAD

**Issue by adelbridge** [CodeandCoffeeCommunity/speaking#34]
## About You

**Your Name:** Ashley Delbridge

**Twitter or Linkedin handle (optional):**  https://www.linkedin.com/in/delbridgea/

**The best way to reach out to you:** a.delbridge94@gmail.com

## Your Talk

**Title:** Senior DevOps Engineer

**What your talk is about:**
Introduction into DevOps

**How long will your talk be?**
- [ ] 20-30 minutes
- [ x] 30-45 minutes
- [ ] 60 minutes or more

## Meetup event Copy - Optional
This will show up on your Meetup.com Event page for your talk. [Example event page](https://www.meetup.com/new-york-code-coffee/events/293109456/).

**Event Title:**  Introduction to DevOps

  
**Event Description:**  
DevOps is reshaping the landscape of software development, yet its extensive nature can pose a challenge when it comes to precise definition. In this workshop, I'll address the fundamental questions: What exactly is DevOps, and why is it crucial? You'll gain insight into the core principles, advantages, and essential tools of DevOps through the interactive session.

**Speaker Bio:**
Senior DevOps engineer with 6 years of experience in cloud migration, infrastructure automation, and systems configuration using AWS and leading cloud technologies.

**Comment by Danamitecoder** [comment]
Spoke to, provided feedback on initial agenda, final deck review, scheduled, meetup event is ready to be posted.
