### ISSUE TITLE
[Talk]: Assessing Frontend Landscape by Charlie Greenman

### ISSUE THREAD

**Issue by CharlieGreenman** [CodeandCoffeeCommunity/speaking#35]
## About You
I am a Software Architect who has consulted for multiple Fortune 500 companies spanning over 10+ years. I am also the Founder of Razroo, a Software Architect as an Application.

**Your Name:**
Charlie Greenman

**Twitter or Linkedin handle (optional):** 
https://twitter.com/razroo_chief

**The best way to reach out to you:**
Email: charlie@razroo.com

## Your Talk
Assessing the Frontend Landscape. Go through the popular frameworks such as Angular/Analog, React/Next, Svelte/SvelteKit, and Vue. Discuss popularity in the job market, the complexity of frameworks, and how much it costs to set up. Discuss some of the latest technologies entering the space such as Bun, Astro, current version experiments with WASM, and what that means.

**Title:**
Exploring the Wild Frontend Frontier: Unveiling it All! 

**What your talk is about:**
Go through the popular frameworks such as Angular/Analog, React/Next, Svelte/SvelteKit, and Vue. Discuss popularity in the job market, the complexity of frameworks, and how much it costs to set up. Discuss some of the latest technologies entering the space such as Bun, Astro, current version experiments with WASM, and what that means. Will be very data-heavy, as well as theorizing where things are headed.

**How long will your talk be?**
- [x] 20-30 minutes
- [ ] 30-45 minutes
- [ ] 60 minutes or more

## Meetup event Copy - Optional
This will show up on your Meetup.com Event page for your talk. [Example event page](https://www.meetup.com/new-york-code-coffee/events/293109456/).

**Event Title:**   
  
**Event Description:**  

**Speaker Bio:**

**Comment by Danamitecoder** [comment]
Emailed 9/27

**Comment by CharlieGreenman** [comment]
@Danamitecoder if can send again i did not receive yet

**Comment by Danamitecoder** [comment]
Haha yes, I commented before sending the email - it's sent now. Let me know if you did not receive it :)

**Comment by CharlieGreenman** [comment]
i got it, awesome
