### ISSUE TITLE
SQL Workshop: Basics and Beyond

### ISSUE THREAD

**Issue by charlesinwald** [CodeandCoffeeCommunity/speaking#36]
## About You

**Your Name:** 
Charles Inwald
**Twitter or Linkedin handle (optional):** 
https://www.linkedin.com/in/charles-inwald/
**The best way to reach out to you:**
Phone or Discord (username: cinwald)
## Your Talk

**Title:**
SQL Workshop: Basics and Beyond
**What your talk is about:**
An SQL crash course, followed by hands on programming exercises for all experience levels.  We'll be using an online SQL playground so all you'll need is a laptop with a browser.

**How long will your talk be?**
- [ ] 20-30 minutes
- [ ] 30-45 minutes
- [X] 60 minutes or more 

[Presentation Slides](https://docs.google.com/presentation/d/1tAyg4YZ9zQZVnyIC3U-Y0HpINYKEMIEFzLeVFSKSB8A/edit?usp=sharing)

[SQL Worksheet](https://docs.google.com/document/d/1tNV8Rm4E86C4SxK9c90tXKnzYfYKRFA7Po--YGXCMoc/edit?usp=sharing) - Interview style questions ranging from beginner to advanced

## Meetup event Copy - Optional
This will show up on your Meetup.com Event page for your talk. [Example event page](https://www.meetup.com/new-york-code-coffee/events/293109456/).

**Event Title:**   
  SQL Workshop: Basics and Beyond
**Event Description:**  
An SQL crash course, followed by hands on programming exercises for all experience levels.  We'll be using an online SQL playground so all you'll need is a laptop with a browser.
![](https://www.sqlshack.com/wp-content/uploads/2020/02/illustration-of-what-the-foreign-key-is.png)

**Speaker Bio:**
Former Apple Engineer, previously worked in startups as a frontend developer

**Comment by SteveChenDC** [comment]
Before Charles posted this, I had already popped it on the Google Events calendar for Oct 22.

**Comment by SteveChenDC** [comment]
@Danamitecoder after this upcoming Oct 8th event. You can post it on meetup alongside the other Oct 22 event.

**Comment by Danamitecoder** [comment]
@SteveChenDC sure thing!

**Comment by charlesinwald** [comment]
![SQL Workshop Graphic](https://github.com/CodeandCoffeeCommunity/speaking/assets/29070037/4ed3add5-3cec-43f3-8535-e7963d2e50ef)

**Comment by Danamitecoder** [comment]
Thanks!
