### ISSUE TITLE
Request to give a talk

### ISSUE THREAD

**Issue by SerenaCapsule** [CodeandCoffeeCommunity/speaking#4]
## About You
I am currently in a backend software engineer in a NYC health care company. I love Python, system design, microservice, Machine Learning, etc.

**Your Name:**
Serena Xu

**The best way to reach out to you:**
Linkedin: https://www.linkedin.com/in/serena-su-xu/

## Your Talk

**Title:**
What I learnt by being a software engineer for 3 years

**What your talk is about:**
Something I learnt by being a software engineer for 3 years, tips and suggestions etc.

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [x] 20-30 minutes
- [x] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [x] Yes
- [ ] No

**Comment by SteveChenDC** [comment]
Thanks for the talk submission! I'd love to see if we can get something up after our Jan 22nd event. 

I've tagged @Danamitecoder to reach out to help craft and refine the talk. She'll reach out through LinkedIn!

@SerenaCapsule any ideas off the top of your tongue you think may be interesting to new devs or your former pre-career self 4 years ago?

**Comment by Danamitecoder** [comment]
Hi! I met with @SerenaCapsule  today and we spoke about possible topics she'd like to explore in her talk. We settled on talking about her journey into software engineering and some lessons she's learned so far as a backend software engineer. She will close with a Q+A.  Would the Feb 5 meetup work for the talk? She said she could get slides ready by Jan 28/29 for our review. After she creates the slides, we could do a quick zoom meeting for her to go over it with us and it would also be an opportunity for us to provide some feedback to her.

**Comment by SteveChenDC** [comment]
That works!

I'll tentatively block off some time for Feb 5th on the internal organizer calendar, then see if it's ready on the 28/29th. 

@SerenaCapsule super excited for this and I greatly appreciate you contributing to C&C with your talk! Please feel free to reach out to Dana or me if you have any questions

**Comment by SteveChenDC** [comment]
I am closing this issue.  

@SerenaCapsule, please re-open and lettuce know if you ever want to do one; I'm genuinely looking forward to it! Super down to help in any way; we're easy.

In the meantime, we updated the Readme with the process; check it out https://github.com/CodeandCoffeeCommunity/speaking lmk if you have any advice!
