### ISSUE TITLE
Building Meetups & User Groups: Principles, Prescriptions, & Power

### ISSUE THREAD

**Issue by SteveChenDC** [CodeandCoffeeCommunity/speaking#43]
## About You

**Your Name:** Steve Chen

**Twitter or Linkedin handle (optional):** linkedin.com/in/stevechendc

**The best way to reach out to you:**
Text/SMS or any of our connected apps. I'm reachable usually!

## Your Talk

**Title:** Building Meetups

**What your talk is about:**
idk we can probably talk shit about a couple communities that sold out.

**How long will your talk be?**
- [x] 20-30 minutes
- [ ] 30-45 minutes
- [ ] 60 minutes or more

## Meetup event Copy - Optional
This will show up on your Meetup.com Event page for your talk. [Example event page](https://www.meetup.com/new-york-code-coffee/events/293109456/).

**Event Title:** Building Meetups & User Groups: Principles, Prescriptions, & Power

**Event Description:**  
_How do you go from 10 to 367 in-person events in 27 US cities in just two years?_

In this talk, you'll learn about the principles behind community-led meetups and prescriptive steps when starting additional meetups or user groups. We'll discuss ways you can collaborate for effective change as we hop into another round of layoffs.

Join Steve Chen, the Executive Director and Founder of the Code & Coffee collective. An in-person meetup collective with over 27 chapters in 27 US cities hosting monthly and bi-weekly events consistently, on a shoestring budget. 

**Takeaways:**
- The three community principles to build any thriving community.
- Prescriptive principles to uphold when running meetups or user groups. 
- How Community-Led and Company-Led communities can come together to change the world. 

Steve drove over 20 times from DC to NYC to bring back in-person developer meetups across the US from 2021 through 2022. Code & Coffee has hosted over 1,000 events on Meetup and across the United States—their mission is to facilitate coding meetups for developers to make new friends and grow. 

Find out more about the movement at CodeAndCoffee.org.

**Speaker Bio:**
Steve Chen is the Head of Community at Sift AI and founder of NYC Code & Coffee Meetup and the Code & Coffee Collective.

**Comment by Danamitecoder** [comment]
No worries! We can schedule a meeting after you put together the first draft of the deck :)

**Comment by Danamitecoder** [comment]
Scheduled meeting!
