### ISSUE TITLE
Command Line Essentials

### ISSUE THREAD

**Issue by charlesinwald** [CodeandCoffeeCommunity/speaking#45]
## About You

**Your Name:** Charles Inwald

**Twitter or Linkedin handle (optional):**  https://www.linkedin.com/in/charles-inwald/

**The best way to reach out to you:** Discord, LinkedIn

## Your Talk

**Title:** Command Line Essentials

**What your talk is about:**
Dive into the world of command line tools in this hands-on workshop, designed to teach you why the CLI is crucial for software development and IT. Just bring a laptop with a web browser to participate in the activity.

**How long will your talk be?**
- [ ] 20-30 minutes
- [ ] 30-45 minutes
- [ X] 60 minutes or more

## Meetup event Copy - Optional
This will show up on your Meetup.com Event page for your talk. [Example event page](https://www.meetup.com/new-york-code-coffee/events/293109456/).

![CommandLineEssentialsWorkshop](https://github.com/CodeandCoffeeCommunity/speaking/assets/29070037/bd916360-e1c5-4428-8878-0490eb21307f)

**Event Title:**   Command Line Essentials
  
**Event Description:**  Dive into the world of command line tools in this hands-on workshop, designed to teach you why the CLI is crucial for software development and IT. Just bring a laptop with a web browser to participate in the activity.

[Slides](https://docs.google.com/presentation/d/14L8ANghVlDRe_ttwrNgs5ZP_dCDuzdXR1nVpOBTIg0s/edit?usp=sharing)

[Activity](https://docs.google.com/document/d/1q0lxm67epC7KpL98yJdJvgRc5GMfdRVKvBd3dP1LQ3Y/edit?usp=sharing) 

**Speaker Bio:**
Former Apple Engineer, previously worked in startups as a frontend developer

**Comment by Danamitecoder** [comment]
Presenting 2/25
