### ISSUE TITLE
 Introduction to Procedural World Generation for Video Games

### ISSUE THREAD

**Issue by squoraishee** [CodeandCoffeeCommunity/speaking#46]
## About You

**Your Name:**

Shafik Quoraishee

**Twitter or Linkedin handle (optional):** 

https://www.linkedin.com/in/shafik-quoraishee/

**The best way to reach out to you:**

https://www.linkedin.com/in/shafik-quoraishee/

## Your Talk

**Title:** Introduction to Procedural World Generation for Video Games

**What your talk is about:**

My presentation will embark on an exploratory journey into procedural world generation, a cornerstone technique in crafting vast, dynamic, and intricate virtual environments. By procedural world generation, I refer to the algorithm-driven process of automatically creating video game worlds in real-time, a method that eliminates the need for manual content creation, thereby revolutionizing the landscape of video games, simulations, and digital art.

Unlike traditional content creation methods that rely heavily on manual design and implementation, procedural generation leverages mathematical and algorithmic formulas to produce diverse and complex outcomes. This approach not only fosters creativity and innovation but also paves the way for generating boundless virtual universes, each unique from the last.

This is not an AI specific talk, but I will attempt to touch on a number of fascinating mathematical and numerical concepts that will assist you in understanding world creation theory.

Example:

Vast, explorable universes in games like "No Man's Sky" or the intricate dungeon labyrinths in "Diablo" demonstrated the power of procedural dungeon creation. These are not handcrafted to the last detail by designers but are instead generated through sophisticated algorithms that can create millions of unique experiences. This method mirrors nature's own processes, where simple rules can lead to complex patterns and structures.

Components of my talk:

* Tracing the roots of this fascinating concept back to its inception and its evolution over the years.   
* Delving into the algorithms and methods that form the backbone of procedural world generation, from Perlin noise to fractal landscapes and cellular automata.
* A look back at key moments in procedural generation history, highlighting landmark games and applications that pushed the boundaries of what's possible.
* Demonstrating the application of these techniques in creating dynamic game worlds, realistic terrains, and complex ecosystems.
* I will showcase examples demonstrating basic to advanced procedural generation techniques, providing attendees with a hands-on understanding of how to implement these concepts.

Notes:

This talk is designed to be comprehensive yet accessible, aiming to demystify the complex algorithms behind procedural generation and make them understandable to a broad audience.  Through live demos and interactive examples, I plan to engage the audience, illustrating the practical applications of these techniques and inspiring attendees to explore the endless possibilities that procedural generation can offer.

**How long will your talk be?**
- [ ] 20-30 minutes
- [ ] 30-45 minutes
- [x ] 60 minutes or more

## Meetup event Copy - Optional
This will show up on your Meetup.com Event page for your talk. [Example event page](https://www.meetup.com/new-york-code-coffee/events/293109456/).

Event Title:
Introduction to Procedural World Generation for Video Games

Event Description:
This presentation will embark on an exploratory journey into procedural world generation, a cornerstone technique in crafting vast, dynamic, and intricate virtual environments. By procedural world generation, we refer to the algorithm-driven process of automatically creating worlds in real-time, a method that eliminates the need for manual content creation, thereby revolutionizing the landscape of video games, simulations, and digital art.

Speaker Bio:
Shafik Quoraishee is a Senior Android/ML Engineer at the New York Times working on the NYT Games team on the integration of games such as Crosswords, Wordle, Connections, and Suduko. He also has on ML research in the Visual/Image Processing space. He has several academic ML based publications in prominent Engineering Journals such as IEEE and SPIE from his time working as an infield Signals Processing research, and he teaches Data Science as well.

**Comment by Danamitecoder** [comment]
Met at code & coffee. Spoke about the talk. Reviewed and scheduled.
