### ISSUE TITLE
Programming Languages: Syntax and Semantics

### ISSUE THREAD

**Issue by charlesinwald** [CodeandCoffeeCommunity/speaking#49]
## About You

**Your Name:**
Charles Inwald
**Twitter or Linkedin handle (optional):** 
https://www.linkedin.com/in/charles-inwald/
**The best way to reach out to you:**
LinkedIn
## Your Talk

**Title:**
Programming Languages: Syntax and Semantics

**What your talk is about:**
Join us for an engaging workshop on "Programming Languages: Syntax vs Semantics"! Dive into the core of programming languages, where we'll explore the intricate details of syntax—the rules and structure of language code—and semantics, the meaning behind the code.  There will be a lecture and a coding activity, so bring a laptop with a web browser to participate in the activity.

**How long will your talk be?**
- [ ] 20-30 minutes
- [ ] 30-45 minutes
- [ X] 60 minutes or more

![  Programming Languages: Syntax and Semantics](https://i.imgur.com/Y0xz76r.png)

## Meetup event Copy - Optional
This will show up on your Meetup.com Event page for your talk. [Example event page](https://www.meetup.com/new-york-code-coffee/events/293109456/).

[Slides](https://docs.google.com/presentation/d/12FZfQlsI5YzIJNkvghZjv9Nd4sF5eCx6jTCu_4AhiRg/edit?usp=sharing)
[Activity](https://docs.google.com/document/d/1V95Bp02zghtc4QO74sGIE0pOHm6xptAgd3CGhJcn_ds/edit?usp=sharing)
**Event Title:**   
  Programming Languages: Syntax and Semantics

**Event Description:**  
Join us for an engaging workshop on "Programming Languages: Syntax vs Semantics"! Dive into the core of programming languages, where we'll explore the intricate details of syntax—the rules and structure of language code—and semantics, the meaning behind the code.  There will be a lecture and a coding activity, so bring a laptop with a web browser to participate in the activity.
**Speaker Bio:**
Former Apple Engineer, previously worked in startups as a frontend developer

**Comment by Danamitecoder** [comment]
Schedueld for 4/7
