### ISSUE TITLE
A beginner workshop to Microservice with Python FastAPI

### ISSUE THREAD

**Issue by yizongk** [CodeandCoffeeCommunity/speaking#5]
## About You

**Your Name: Yi Zong Kuang**

**The best way to reach out to you: email: yizongk@gmail.com**

**A quick bio:**
I have worked with API for over 3.5+ years, at NYC DOT, and currently at Mastercard. During my time at DOT, I have built several internal Web Apps in Django, worked with its ORM with SQL Server, and front end data grid view/editing designs. 
Right now at Mastercard, I am working with Java Springboot to build Mastercard's first ever Crypto Buy/Sell/Transfer Service (It has yet to be in Production, it will be live within this year). We are building our APIs in a Microservice architecture and is the reason I want to do workshop sharing what I know about building APIs in a Microservice architecture.

## Your Talk

**Title: Building APIs in a Microservice architecture with Python FastAPI (Beginner)**

**What your talk is about:**
It will include an introduction to what a Micro Service is, and what are its Pros and Cons versus the traditional Monolithic architecture. We will also talk about when we should use Microservice and when it's better to stick with the traditional Monolithic Architecture. Following it, a workshop where attendees will get their hands dirty building a Microservice (assisted with live coding) of a Word Cup Casino mock. Then finishing off with possible ideas to scale the Microservice once the Minimal Viable Product is finished (It would be using Kafka to help with the scaling problem, which could a future workshop that adds Kafka on top of the World Cup Casino APIs built in this workshop).

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [ ] 30-45 minutes
- [X] 60 minutes or more

Probably will take close to 60 mins, I don't think it will take longer, the time really depends on how much installation/trouble shooting issues comes up.

## Meta
Note, I would like this workshop to be a small one to begin with, as this is the first time I am holding a workshop (20 people max). I want to use this small size to better hone my public speaking skills first before attempting an larger audience.

**Do you need help crafting your talk?**
- [ ] Yes
- [ ] No
- [X] Maybe, what help can you provide?

**Comment by Danamitecoder** [comment]
Hi Yi Zong,

I can provide tips on structuring your talk, increasing audience engagement and differentiating the talk for devs of all experience and backgrounds.  You can do a practice round with Steve (if he's available) and I. Maybe we can set up a meeting first to discuss the content and your goals for the talk? 

Thanks!
Dana
