### ISSUE TITLE
Algorithms and Data Structures Talk - Recursion

### ISSUE THREAD

**Issue by polancojoseph1** [CodeandCoffeeCommunity/speaking#6]
## About You

**Your Name:**
Joseph Polanco
Nickname: Jéfe

**Instagram handle (optional):** 
@jefedelatech

**The best way to reach out to you:**
6466750765 and Instagram

**A quick bio:**

Hello my name is Joseph I just finished a software engineer apprenticeship at Bloomberg LP and just signed an offer to be a Software Engineer at Bloomberg. Before this I was attending 2 coding bootcamps trying to get into the tech industry.

## Your Talk

**Title:**
Algorithms and Data Structures(Recursion

**What your talk is about:**
I’m going to solve 3 leet code problems while talking about the importance of knowing recursion when trying to get a job in big tech. 

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [ *] 20-30 minutes
- [ ] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [*] Yes
- [ ] No

**Comment by Danamitecoder** [comment]
Hey Joseph,

Let's meet sometime so I can support you with the structure of your talk!

Best regards,
Dana

**Comment by mkazin** [comment]
Joseph, Dana-
I recently checked out a great book from the library which does a great job teaching recursion. It helped me improve how I mentor new coders.
I believe it could provide some useful ideas and may be a good resource to recommend to attendees for further reading.
The book is "The Recursive Book of Recursion - Ace the Coding Interview with Python and JavaScript" by Al Sweigart.
Good luck,
Michael
