### ISSUE TITLE
Speaking Ideas for Meetups

### ISSUE THREAD

**Issue by werner33** [CodeandCoffeeCommunity/speaking#8]
---
name: Talk
about: Submit a talk idea to participating meetups.
title: ''
labels: talk
assignees: ''

---

## About You

**Your Name:**
Jordan Manley

**Twitter handle (optional):** 

**The best way to reach out to you:**
jordan@codetrack.dev

**A quick bio:**

Self-taught software engineer with 7 years of experience. For the last two years I have worked as an instructor teaching at Pursuit.org. Prior to that I worked at B&H Photo as a Front End Engineer.

In my free time, I've developed [CodeTrack](https://www.codetrack.dev/), a free platform for guiding and tracking developers to career success. 

## Your Talk

**Title:**
Options: 
1. Leading With Your Work: How to get Interviews with No Resume
2. CodeTrack: How I Built This

**What your talk is about:**

1.Leading With Your Work

When I was looking for my first job, I didn't have anything relevant on my resume. No degree, no highschool diploma, no GED, no relevant work experience. I had to rely on my work to get interviews and then my skill to get me through the interview. 

Here is a link to [an article](https://www.codetrack.dev/articles/one-great-project) touching on the same theme.

Here is a [slide show](https://slides.com/jordanmanley-1/deck) that I might use but it gives a good idea of the talk.

2. CodeTrack: How I Built This

CodeTrack utilizes several APIs in non-traditional ways. It's required creativity and reaching out to some companies to see if they would make changes to their API so that I could integrate with it better. 

CodeTrack is a fun product to explore as it is part education, part game and part resume for developers. 

I would focus on one-two features and break them apart to show how I built them. 

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [x] 20-30 minutes
- [x] 30-45 minutes
- [ ] 60 minutes or more

Happy to do any length, really. 

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [x] No

**Comment by SteveChenDC** [comment]
@werner33 thanks for submitting this! @Danamitecoder mind chatting with Jordan? 

We chatted earlier this week over a call and met him in person at the last event!

**Comment by Danamitecoder** [comment]
Hello @SteveChenDC  and @werner33 ! 
Took a quick look at the article/presentation you shared. I think your talk would be of high interest for our participants! Would you be available for a quick chat sometime this week?

**Comment by Danamitecoder** [comment]
We have space this Sunday 2/5 following another presentation, would you be interested in giving this talk then? I'm not available at 2pm tomorrow but could do anytime after 6pm for a quick chat or anytime before noon on Saturday. Please let me know. Thanks!

**Comment by werner33** [comment]
This Sunday would be fine.

I'll probably give the first of the two talks I mentioned about leading
with your work to land a job.

Can we talk at 10am on Saturday?

Thanks and looking forward!

**Comment by Danamitecoder** [comment]
Wonderful!! Talk to you at 10am on Saturday!
