### ISSUE TITLE
Hacking Wordle For Fun (No profit)

### ISSUE THREAD

**Issue by kablaa** [CodeandCoffeeCommunity/speaking#9]
## About You

Tyler Lukasiewicz 

**Discord: goron#7687**

I have been doing cyber security for almost 10 years and have been working professionally in the field for the last 7 years. I am currently working as a Security Engineer at Google.

## Your Talk

**Hacking Wordle For Fun (No profit) **

[Wordle](https://www.nytimes.com/games/wordle/index.html?success=true) is a fun game where people try guess the word of the word of the day.  Players have six attempts to guess a five-letter word, with feedback given for each guess in the form of colored tiles indicating when letters match or occupy the correct position. However, the developers haven't put much thought into the games security and thus it possible to get the word of the day via inspecting the client-side JavaScript. My talk will cover: 

* The basics of front-end vs backend logic
* javacript packing 
* cookies and how they are used by websites 
* How to use the 'inspect element' tab in Chrome
* a live demo of how to hack Wordle. This will include 
   1. Giving yourself unlimited guesses 
   2.  Getting the word of the day on the first try every time
 * finally, I will talk a bit about game security and what the devs could do to prevent this 

**How long will your talk be?**
- [ ] 5-15 minutes (lightning talk)
- [ ] 20-30 minutes
- [* ] 30-45 minutes
- [ ] 60 minutes or more

## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [ *] No

## Meetup event Copy - Optional
**Event Title:**   
  
**Event Desciption:**

**Comment by SteveChenDC** [comment]
@Danamitecoder could you get in contact with Tyler? 

Dana or I will reach out to you shortly to get more details about your talk and maybe schedule it for an upcoming event. We recently documented the process https://github.com/CodeandCoffeeCommunity/speaking

**Comment by Danamitecoder** [comment]
Hi Tyler @kablaa! Great topic! When would you be available for a quick chat to talk about next steps?

**Comment by kablaa** [comment]
I can usually take some time around noon on most weekdays. Maybe Monday at Noon? That will give me some time to put together a more cohesive outline.

**Comment by Danamitecoder** [comment]
Sure! That works for me. I will add you on discord and we can do a voice call from there. Have a nice weekend and talk to you soon!

**Comment by SteveChenDC** [comment]
Booked for upcoming Mar 5th in NYC
